# Site settings
title: "Traveled"
header-img: img/zion.jpg
email: cjirmas@gmail.com
description: Cameron Irmas - Blog
baseurl: ""
url: "http://camirmas.github.io"
twitter_username: cam_irmas
github_username:  camirmas
facebook_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
