# Site settings
title: Blog
header-img: img/profile.jpeg
email: your-email@yourdomain.com
description: Cameron Irmas - Blog
baseurl: ""
url: "http://camirmas.github.io"
twitter_username: cam_irmas
github_username:  camirmas
facebook_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
